### ISSUE TITLE
Requests for https://biocache.ala.org.au/ws/mapping/legend?null

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-hubs#253]
Requests are being made for ``https://biocache.ala.org.au/ws/mapping/legend?null``, which are being returned with HTTP 400. It doesn't seem like the request should have been made in the first place, instead, it possibly should have errored or made a different request.

This is the stacktrace from biocache-b3 today:

```
2018-02-27 06:32:26,434 ERROR [WebServicesService] Failed to get json from web service (https://biocache.ala.org.au/ws/mapping/legend?null). class java.io.IOException Server returned HTTP response code: 400 for URL: https://biocache.ala.org.au/ws/mapping/legend?null, java.io.IOException: Server returned HTTP response code: 400 for URL: https://biocache.ala.org.au/ws/mapping/legend?null
2018-02-27 06:32:26,439 ERROR [GrailsExceptionResolver] RestClientException occurred when processing request: [GET] /occurrence/legend
Failed to get json from web service (https://biocache.ala.org.au/ws/mapping/legend?null). class java.io.IOException Server returned HTTP response code: 400 for URL: https://biocache.ala.org.au/ws/mapping/legend?null, java.io.IOException: Server returned HTTP response code: 400 for URL: https://biocache.ala.org.au/ws/mapping/legend?null. Stacktrace follows:
org.springframework.web.client.RestClientException: Failed to get json from web service (https://biocache.ala.org.au/ws/mapping/legend?null). class java.io.IOException Server returned HTTP response code: 400 for URL: https://biocache.ala.org.au/ws/mapping/legend?null, java.io.IOException: Server returned HTTP response code: 400 for URL: https://biocache.ala.org.au/ws/mapping/legend?null
	at au.org.ala.biocache.hubs.WebServicesService.getJsonElements(WebServicesService.groovy:395)
	at au.org.ala.biocache.hubs.WebServicesService.getMapLegend(WebServicesService.groovy:61)
	at au.org.ala.biocache.hubs.OccurrenceController.legend(OccurrenceController.groovy:320)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:189)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
