### ISSUE TITLE
Error when displaying records

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/biocache-hubs#552]
As reported, some records failed to be displayed on biocache. 
https://biocache.ala.org.au/occurrences/64c8d41d-9672-40d1-bb46-67afdeb7124a
https://biocache.ala.org.au/occurrences/9622d13a-4a86-4a60-9f6c-ed3a0e94ba7d

The following error is shown in ala-hubs.log

```
2022-07-20 10:01:01.380 ERROR --- [.1-8080-exec-71] o.s.boot.web.support.ErrorPageFilter     : Forwarding to error page from request [/occurrences/9622d13a-4a86-4a60-9f6c-ed3a0e94ba7d] due to exception [Error processing GroovyPageView: [views/occurrence/show.gsp:217] Error executing tag <g:render>: [views/occurrence/_recordCore.gsp:266] Error executing tag <alatag:occurrenceTableRow>: No signature of method: org.grails.web.json.JSONArray.toLowerCase() is applicable for argument types: () values: []]

org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/occurrence/show.gsp:217] Error executing tag <g:render>: [views/occurrence/_recordCore.gsp:266] Error executing tag <alatag:occurrenceTableRow>: No signature of method: org.grails.web.json.JSONArray.toLowerCase() is applicable for argument types: () values: []
	at org.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:135)
	at org.grails.web.servlet.view.GroovyPageView.handleException(GroovyPageView.java:112)
	at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:80)
	at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
	at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
```

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/c9c5669fc0957faddd4882fa3a718e804689dad8

**Comment by sat01a** [comment]
@javier-molina over to you for testing

**Comment by javier-molina** [comment]
Of course as suspected this affects AVH as well

https://avh.ala.org.au/occurrences/453834e0-2065-4652-b0b1-a84905a4b35a 
https://avh.ala.org.au/occurrences/1d12fb41-7398-44d7-9701-833ae87bcea2

**Comment by timhicks-ala** [comment]
3 additional examples in this search: https://biocache.ala.org.au/occurrences/search?q=lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Ffungi%2F60088179&qualityProfile=ALA&radius=25&lat=-38.34424057296562&lon=144.1713872551918#tab_recordsView
